# Site settings
title: 小银枪的博客
SEOTitle: ▄︻┻┳═一✨ | Blog
header-img: img/post-bg-desk.jpg
email: rp599207211@gmail.com
description: "товарищ,Ура!"
keyword: "小银枪的博客, SilverSpear1031, 马鞍山小银枪, Machine Learing, Java, Python, Scala"
url: "http://SilverSpear1031.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/SilverSpear1031/SilverSpear1031.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "He's too lazy to left anything"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     2287397493
zhihu_username:     rui-peng-73
github_username:    SilverSpear1031
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate,jekyll-sitemap]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
# disqus_username: SilverSpear1031

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8b47188a2cfafd755247   #生成的clientID
  clientSecret: 26f6b522dac2ca620658ef84f42897155ee67174  #同上
  repo: SilverSpear1031.github.io    #仓库名称
  owner: SilverSpear1031    #github用户名
  admin: SilverSpear1031
  distractionFreeMode: true #是否启用类似FB的阴影遮罩




# Analytics settings
# Baidu Analytics
ba_track_id: 8ed5c06423aa1e0e95bd9ca6fc093cb2

# Google Analytics
ga_track_id: 'UA-109551824-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Github",
        href: "https://github.com"
    }
]
